# Generated by Django 2.0 on 2017-12-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten_url', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='id',
        ),
        migrations.RemoveField(
            model_name='url',
            name='shoretened_url',
        ),
        migrations.AddField(
            model_name='url',
            name='code',
            field=models.CharField(default='', max_length=8, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
